version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bike-fitter-db
    restart: unless-stopped
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
